project:
  type: website
  
website:
  title: "Joshua Puyear"
  page-footer: 
    left: "@JPuyear, 2026" 
    right:
      - icon: github
        href: https://github.com/JPuyear
      - icon: linkedin
        href: https://linkedin.com/in/joshua-puyear
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about-page.qmd
        text: About Me
      - href: projects.qmd
        text: Studies and Projects
      - href: resume.qmd
        text: Resume Highlights
      
     
format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
